### ISSUE TITLE
mod_gwpayments generate duplicate rows.

### ISSUE THREAD

**Issue by Snickser** [iplusacademy/report_payments#3]
Hi!

Select returns duplicate rows from unused course.

![изображение](https://github.com/iplusacademy/moodle-report_payments/assets/88129688/8fb939e0-0248-4910-91aa-3d77d6d170e7)

**Comment by Snickser** [comment]
Use this

        $course->add_join("JOIN {modules} m on {$mainalias}.component=CONCAT('mod_',m.name)");
        $course->add_join("JOIN {course_modules} cm on (m.id=cm.module and {$mainalias}.itemid=cm.instance)");
        $course->add_join("JOIN {course} {$coursealias} on {$coursealias}.id=cm.course");

![изображение](https://github.com/iplusacademy/moodle-report_payments/assets/88129688/c45d95ed-7b64-4a9d-a976-822da9d4b84e)

**Comment by iplusacademy** [comment]
Thank you for the error report. 

I have seen this error during the devellopment of this plugin, but I thought is was gone.
First I will try to replicate this in Behat tests.

**Comment by Snickser** [comment]
It occurs if the payer is registered in more than one course, since your request looks at course entries. And my request pulls out the name of the course through the number of the element from which the payment was made, since this is a unique number.

**Comment by iplusacademy** [comment]
I do not understand your solution because enrolment has nothing to do with modules. 
Do you use a module based enrolment?

**Comment by Snickser** [comment]
My example for payments through the course activity module (mod_gwpayments), I do not use course registration payment (enrol_fee).

**Comment by iplusacademy** [comment]
Payments in Moodle are stored using the function save_payment with these parameters
int $accountid,
string $component,
string $paymentarea,
int $itemid,
int $userid,
float $amount,
string $currency,
string $gateway

So the solution should be related to one of these columns, and not in course modules.

The mod_gwpayments was not maintained for 2 years.. Should there be support for outdated plugins?

**Comment by Snickser** [comment]
There are three places where you can accept payments, enroll in courses, the active course module and the course section, although there are likely to be other options. But your module only supports enrol, which somewhat limits its functionality and leads to duplicate lines. I personally would like this to be fixed...
For example, my system uses all three methods.
```
MariaDB [moodledb]> select component from mdl_payments group by component;
+-------------------------+
| component               |
+-------------------------+
| availability_gwpayments |
| enrol_fee               |
| mod_gwpayments          |
+-------------------------+
3 rows in set (0.000 sec)
```
Therefore, it seems logical to take the name of the course not by enrol (or only by enrol module?), but through the component + itemid parameter. Unfortunately, this requires much more complex queries.
In any case, it would be nice to get rid of duplicate lines.

**Comment by iplusacademy** [comment]
Can you provide the content of a repeated row from your mdl_payments table? After all this plugin is nothing more than a html output of the mdl_payments table. If rows are repeated, the solution should be found there.

**Comment by Snickser** [comment]
[mdl.dump.gz](https://github.com/iplusacademy/moodle-report_payments/files/15374232/mdl.dump.gz)

**Comment by iplusacademy** [comment]
If I make a payment with PayPal 1 record is added to the enrol_paypal table.  If I make a payment with enrol_fee, 1 record is added to the payments table.   Your table has duplicate entries. 

The only reason I can imagine that a payment generates 2 entries when one entry is added from a callback,  another from a java script.  This is because I see a payment for one course, and within 2 or 3 seconds, another payment  from the same user to another course. Or this user is extremely skillfull and working fast in different windows, or this plugin generates 2 payment entries.

I do not understand why the availability gwpayments adds multiple records with the same amount . But your table shows that a user has payed 1000 for each module.

The comment of the payments table is clear:   [Stores information about payments](https://github.com/moodle/moodle/blob/main/lib/db/install.xml#L4496).  So if your plugins generate multiple records, then they are shown in the report.

**Comment by Snickser** [comment]
Because this is a dump from a test server, and all those entries appeared during development. But if you enable the display of the transaction number (payment id), you will notice that the lines on request are duplicated, although there are no duplicate records in the database.

![изображение](https://github.com/iplusacademy/moodle-report_payments/assets/88129688/12c39e22-b5ec-4ab8-8794-6b1e86dae187)
